replicaCount: 1

namespace: openstack

image:
  repository: hemsonawane/bind9
  tag: latest
  pullPolicy: Always

service:
  type: NodePort

nodeSelector:
  openstack-control-plane-dns2: enabled

namedConf: |
  include "/etc/rndc.key";
  options {
    listen-on port 63 { 192.168.101.49; };
    directory "/var/lib/bind";
    allow-new-zones yes;
    dnssec-validation yes;
    auth-nxdomain no;
    request-ixfr no;
    recursion no;
    minimal-responses yes;
    allow-notify { 192.168.101.49; };
  };

  controls {
    inet 192.168.101.49 port 963 allow { 192.168.101.49; } keys { "rndc-key"; };
  };

rndcKey: |
  key "rndc-key" {
    algorithm hmac-sha256;
    secret "XUTO6iQhAZj8gUFL1OB63EyezIvT6bfjU7Z4o24J+nM=";
  };

rndcConf: |
  include "/etc/rndc.key";
  options {
    default-key "rndc-key";
    default-server 192.168.101.49;
    default-port 963;
  };

