apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-config
  namespace: {{ .Values.namespace }}
data:
  named.conf: |
{{ .Values.namedConf | indent 4 }}
  rndc.key: |
{{ .Values.rndcKey | indent 4 }}
  rndc.conf: |
{{ .Values.rndcConf | indent 4 }}
