apiVersion: v1
kind: Service
metadata:
  name: bind9
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: dns-tcp
      port: 63
      targetPort: 63
      protocol: TCP
    - name: dns-udp
      port: 63
      targetPort: 63
      protocol: UDP
  selector:
    app: bind9

